services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '%kernel.project_dir%/src/*'
    exclude: '%kernel.project_dir%/src/{Entity,Migrations,Tests,DataFixtures}'

  App\Controller\:
    resource: '%kernel.project_dir%/src/Controller/'
    tags: ['controller.service_arguments']