parameters:
  app.crypto.key: '%env(string:CRYPTO_KEY)%'
  app.crypto.nonce: '%env(string:CRYPTO_NONCE)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $cryptoNonce: '%app.crypto.nonce%'
      $cryptoKey: '%app.crypto.key%'

  Symfony\Component\Serializer\Serializer: ~

  App\Component\Serializer:
    decorates: Symfony\Component\Serializer\Serializer
    arguments: ['@serializer.inner']

  App\Security\CryptoSecret: ~

  App\Security\Encoder\MessageEncoder: ~
  App\Security\Encoder\MessageEncoderInterface: '@App\Security\Encoder\MessageEncoder'

  App\Security\Decoder\MessageDecoder: ~
  App\Security\Decoder\MessageDecoderInterface: '@App\Security\Decoder\MessageDecoder'

  App\Controller\:
    resource: '%kernel.project_dir%/src/Controller/'
    tags: ['controller.service_arguments']

  App\:
    resource: '%kernel.project_dir%/src/*'
    exclude: '%kernel.project_dir%/src/{Entity,Migrations,Tests,DataFixtures,DTO,Exception}'