doctrine_migrations:
    dir_name: "%kernel.project_dir%/config/migrations"
    namespace: DoctrineMigrations
    name: Local Application Migrations
    organize_migrations: false
    table_name: migration_versions