version: '3.7'

services:
  app-fpm:
    build:
      context: php
      args:
        UID: ${UID}
        GID: ${GID}
    env_file:
      - .env
    volumes:
      - ../web-app:/var/www
    networks:
      - app-network

  app-web-server:
    build:
      context: nginx
      args:
        SERVER_NAME: ${SERVER_NAME}
    volumes:
      - ../web-app/assets:/var/www/assets
    depends_on:
      - app-fpm
    networks:
      - app-network

  app-db:
    image: mysql:${APP_DB_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${APP_DB_USER}
      MYSQL_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - app_db_volume:/var/lib/mysql
    depends_on:
      - app-fpm
    networks:
      - app-network

volumes:
  app_db_volume:

networks:
  app-network:
    driver: bridge