security:
  encoders:
    App\Entity\User:
      algorithm: auto
  providers:
    users:
      entity:
        class: App\Entity\User
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      form_login:
        login_path: login
        check_path: login
        csrf_token_generator: security.csrf.token_manager
        default_target_path: messenger
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
      logout:
        path: logout
  access_control:
    - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/messenger$, roles: IS_AUTHENTICATED_FULLY}
    - { path: ^api/v1/*, roles: IS_AUTHENTICATED_FULLY}