parameters:
  socket_host: '%env(SERVER_NAME)%'
  socket_port: '%env(SOCKET_PORT)%'

twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes: ['bootstrap_4_layout.html.twig']
  globals:
    socketDsn: '%socket_host%:%socket_port%'